[package]
name = "rusty_plants_vs_zombies"
version = "0.1.0"
edition = "2024"

[dependencies]
ggez="0.7.0"
image = "0.25.6"
glam={version="0.30.2",features=["mint"]}
rand = "0.8.5"
async-std = "1.10"
crossbeam="0.8" #multithreaded tools
#lazy_static = "1.4" #global variable